# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-SQLite
version:      0.03
version_from: lib/Class/DBI/SQLite.pm
installdirs:  site
requires:
    Class::DBI:                    0.85
    DBD::SQLite:                   0.07
    Ima::DBI:                      0.27
    SQL::Parser:                   1.004
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
